# Generated by Django 4.2.5 on 2023-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Заголовок'),
        ),
    ]
